[app]
  watchfile_name = "the-watchfile"                   # the name of the file to be passed between machines
  watchfile_dir = "/home/user/rust-watchfile-remote" # the full path to this executable
  sleep_interval = 300                               # interval (in secs) to send the watchfile to the receiver

[receiver]
  username = "username_here"             # remote server account username
  server = "yourdomain.com"              # remote server domain name
  password = "use_ssh_keys"              # password OR keep as default to "use_ssh_keys"
  ssh_key = "/home/user/.ssh/id_ed25519" # full path (on local machine) to ssh certificate
  dir = "/home/user/watchfile-remote"    # full path to receiver executable on remote server
